"""
Core type definitions for the Neuro-Symbolic UXO Framework.

This module defines all dataclasses and type aliases used throughout
the framework for type safety and documentation.
"""
from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional, Set, Tuple, Union


class SystemState(Enum):
    """State of the system after inference."""
    NORMAL = "normal"
    UNCERTAINTY = "uncertainty"


class QueryType(Enum):
    """Type of feedback query to generate."""
    COMPLETENESS = "completeness"
    CONTRADICTION = "contradiction"


@dataclass
class Attribute:
    """
    Represents a visual attribute that can be detected by the VLM.
    
    Attributes are primitive visual features, not technical EOD terms.
    Examples: "elongated_shape", "fins_visible", "cylindrical_body"
    """
    name: str
    description: str
    category: str


@dataclass
class OrdnanceClass:
    """
    Represents an ordnance class from the Knowledge Graph.
    
    Contains the sets of required and forbidden attributes.
  
    """
    name: str
    required_attributes: Set[Union[str, Tuple[str, ...]]] = field(default_factory=set)
    forbidden_attributes: Set[Union[str, Tuple[str, ...]]] = field(default_factory=set)
    supporting_attributes: List[str] = field(default_factory=list)


@dataclass
class ConstraintViolation:
    """
    Represents a violation of a logical constraint.
    
    Used by the PSL validator to track which constraints are violated
    and by how much, enabling targeted feedback queries.
    """
    constraint_type: str
    attribute: str
    violation_magnitude: float
    class_name: str
    attribute_group: Optional[Tuple[str, ...]] = None


@dataclass
class PSLResult:
    """
    Result of PSL consistency validation using HL-MRF optimization.
    
    Contains the optimized P(y) values from solving the convex optimization
    problem as defined in Paper Eq. 3-4.
    """
    total_energy: float
    class_name: str
    violations: List[ConstraintViolation]
    individual_energies: Dict[str, float]
    optimized_posteriors: Optional[Dict[str, float]] = None
    objective_energy: Optional[float] = None


@dataclass
class FeedbackQuery:
    """A targeted query generated by the feedback mechanism."""
    attribute: str
    query_type: QueryType
    prompt: str
    violation_magnitude: float


@dataclass
class SafeguardResult:
    """Result of safeguard checks."""
    state: SystemState
    reason: Optional[str]
    can_proceed: bool


@dataclass
class InferenceResult:
    """
    Final result of the neuro-symbolic pipeline.

    Contains the predicted class, risk level, confidence,
    system state, and a reasoning trace for auditability.
    """

    predicted_class: str
    # risk_level removed
    confidence: float
    state: SystemState
    reasoning_trace: List[str]
    iterations_used: int
    attribute_confidences: Dict[str, float] = field(default_factory=dict)
    vlm_trace: List[Dict] = field(default_factory=list)
    kg_energies: Dict[str, float] = field(default_factory=dict)
    psl_scores: Dict[str, float] = field(default_factory=dict)
    feedback_details: Dict = field(default_factory=dict)
    timing_ms: Dict[str, float] = field(default_factory=dict)


AttributeConfidences = Dict[str, float]
GraphScores = Dict[str, float]
